### PR TITLE
Add snippets for hook_update_N (for .install files)

### PR DESCRIPTION
**Pull request by DjebbZ**
Missing snippet, especially useful when using code/feature-driven development workflow. Hope you'll add it !

### CODE REVIEW

**Comment by DjebbZ** [comment]
Arf... I edited directly through Github, and I should use double quotes instead of single quotes in the t() message. Feel free to correct this if you prefer double quotes (I do).

**Comment by tanarurkerem** [comment]
Hi, 

First of all, thanks your work!

I prefer single quotes.

I would like to merge this patch, please correct the patch (https://github.com/DjebbZ/drupal-snippets/commit/b00fbafeba12801a6f792043553c4a0efcb3297a#commitcomment-695617).

**Comment by DjebbZ** [comment]
Should be fixed now (stupid mistake)

**Comment by tanarurkerem** [comment]
Merged, thanks.

**Pull request merged**
